# Site settings
title: kuikanmäki
subtitle: "Kirjoituksia"
email: jari.kuikanmaki@gmail.com
description: "Seuraa Twitterissä"
baseurl: ""
url: "https://kuikanmaki.github.io"
twitter_username: "jarikuikanmaki"
github_username:  "kuikanmaki"
instagram_username: "jkuikanmaki"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]