# Site settings
title: Jari Kuikanmäki
subtitle: "Kirjoituksia"
email: jari.kuikanmaki@gmail.com
description: "Blogi"
baseurl: ""
url: "https://kuikanmaki.github.io"
twitter:
username: jarikuikanmaki

# Build settings
markdown: kramdown
permalink: pretty
future: true

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed

# Gems
gems:
    - jekyll-paginate
    - jekyll-seo-tag

# Google services
google_analytics: UA-61093128-1

#Facebook Sharing
facebook_app_id: 1798370233778304